### ISSUE TITLE
[bug?] Run rustic-format-buffer will lose cursor point and jump to beginning of buffer after format.

### ISSUE THREAD

**Issue by zw963** [brotzeit/rustic#156]
But `rustic-cargo-fmt` will keep cursor point position no changed, i think this is expected behavior, so, maybe we need imporve `rustic-format-buffer` ?

**Comment by brotzeit** [comment]
Hmmm yeah I should have tested #103 before I merged it. @tspiteri any idea ?

**Comment by zw963** [comment]
Hi, i tested with 2e42cc4, but it seem like still exist some issue.

if you add many space at the beginning of one line, and then save this buffer, when i invoke
`rustic-format-buffer`, my cursor will skip to next several line unexpected.

BTW: it is not happen on `rustic-cargo-fmt`, thank you.

**Comment by brotzeit** [comment]
I will try it with a marker.

**Comment by tspiteri** [comment]
On what emacs version is the bug observed?

**Comment by zw963** [comment]
> On what emacs version is the bug observed?

Emacs 27.1 on Arch linux.

**Comment by brotzeit** [comment]
Can you please try https://github.com/brotzeit/rustic/commit/b18827106889b0a1a9fcb4a414642cc8b5cfb096

**Comment by brotzeit** [comment]
Btw I added `rustic-format-file`. This could be an alternative.

**Comment by zw963** [comment]
`rustic-format-file` works very nice, thank you!
